version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=wego
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '33306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - db:/var/lib/mysql
  car-park:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      "spring.datasource.url": "jdbc:mysql://db:3306/wego"
      "spring.datasource.username": "root"
      "spring.datasource.password": "root"
      "com.huynguyen.wego.import.enabled": "true"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
volumes:
  db:
    driver: local